In [57]:
import numpy as np

## DataTypes & Attributes 

In [58]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [59]:
type(a1)

numpy.ndarray

In [60]:
a2 = np.array([[1,2,3],[4,5,6.5]])

a3 = np.array([[[1,2,3], 
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18],
              ]])

In [61]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a1.shape

(3,)

In [64]:
a2.shape

(2, 3)

In [65]:
a3.shape

(2, 3, 3)

In [66]:
a1.ndim ,a2.ndim, a3.ndim

(1, 2, 3)

In [67]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [68]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [69]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [70]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [71]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating Arrays

In [72]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [73]:
sample_array.dtype

dtype('int32')

In [74]:
ones = np.ones((2,3))

In [75]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
ones.dtype

dtype('float64')

In [77]:
type(ones)

numpy.ndarray

In [78]:
zeros = np.zeros((2,3))

In [79]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
range_array = np.arange(0, 10, 2)

In [81]:
range_array

array([0, 2, 4, 6, 8])

In [82]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 1, 5, 3, 2],
       [0, 4, 8, 7, 1],
       [4, 9, 3, 6, 7]])

In [83]:
random_array.shape

(3, 5)

In [84]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.63847702, 0.86288872, 0.63662654],
       [0.99929706, 0.51778008, 0.32761664],
       [0.09877324, 0.5667664 , 0.21520794],
       [0.01179079, 0.29921532, 0.03897743],
       [0.97621382, 0.55145308, 0.07171621]])

In [85]:
random_array_2.shape

(5, 3)

In [86]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.34006782, 0.24290239, 0.10735082],
       [0.77033058, 0.35060155, 0.18764274],
       [0.91265269, 0.86114826, 0.39889823],
       [0.54633644, 0.45037544, 0.69359919],
       [0.21384609, 0.3237989 , 0.73989292]])

In [87]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [88]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [89]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [90]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [91]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1

array([1, 2, 3])

In [93]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [94]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [95]:
a1[0]

1

In [96]:
a2[0]

array([1., 2., 3.])

In [97]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [99]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [100]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [101]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [102]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## 4. Manipulating & comparing arrays

### Arithmatic

In [103]:
a1

array([1, 2, 3])

In [104]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [105]:
a1 + ones

array([2., 3., 4.])

In [106]:
a1 - ones 

array([0., 1., 2.])

In [107]:
a1 * ones

array([1., 2., 3.])

In [108]:
a2 

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [109]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [110]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [111]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use and Numpy's methods on Numpy arrays (`np.sum()`).

In [ ]:
# Create a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard Deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the main 
# Higher Variance = wider range of numbers 
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var 
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt 
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & Transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a2 * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3 ,1).shape

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
# Transpose 
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot Product 

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise Multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat2.shape, mat1.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

# Dot product example (nut butter sales) 

In [ ]:
np.random.seed(0)
# Numbers of jars sold 
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales DataFrame 
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut Butter", "Cashew butter"])
weekly_sales

In [ ]:
# Create a prices array
prices = np.array([10,8,12])
prices

In [ ]:
prices.shape

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut Butter", "Cashew butter"])
butter_prices

In [ ]:
prices.shape

In [ ]:
sales_amounts.shape

In [ ]:
total_sales = prices.dot(sales_amounts)

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.T

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparison Operators 

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 == a1

In [ ]:
a1 == a2

## 5. Sorting Arrays

In [ ]:
random_array = np.random.randint(10, size=(3,5))
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmax(a1)

In [ ]:
np.argmax(random_array, axis=0)

In [ ]:
np.argmax(random_array, axis=1)

## 6. Practical Example - Numpy in Action!!!

<img src="panda.png" />

In [122]:
# Turn an image into Numpy Array
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [125]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [127]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="car-photo.png" />

In [129]:
car = imread("car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [131]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src="dog-photo.png" />

In [132]:
dog = imread("dog-photo.png")

print(type(dog))

<class 'numpy.ndarray'>


In [133]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274